---
title: "Dataset creation"
author: "Rita Alvarez and Rafael Schmuziger"
date: "8 de diciembre de 2016"
output: pdf_document
---

```{r options, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(message = FALSE)
# opts_chunk$set(tidy=FALSE)
# opts_chunk$set(fig.path='figs/', cache.path='cache/graphics-', 
#         fig.align='center', fig.width = 5, fig.height = 5, fig.show = 'hold',
#         cache = TRUE, par = TRUE)
```

```{r library, message=FALSE, echo=FALSE, include=FALSE}
library(pxR)
library(MicroDatosEs)
library(XML)
library(zoo)
library(rvest)
library(dplyr)
library(magrittr)
library(foreign)
library(readxl)
#library(xlsx)
library(ggplot2)
library(pastecs)
library(stargazer)
```

```{r set wd, message=FALSE, echo=FALSE, include=FALSE}
setwd('C:/Users/Rita/Desktop/Assignment-3')
```

```{r turnout data, results='asis', tidy=TRUE, echo=FALSE}
# Read Turnout data

Turnout2004_2008_2011_2015 <- read_excel("C:/Users/Rita/Desktop/Assignment-3/ElectionsResult_2015_2011_2008_2004.xlsx", col_names = TRUE)
```

```{r unemployment data, results='asis', tidy=TRUE, echo=FALSE}
# Read Unemployment data

YouthUnemployment2004_2015 <- read_excel("C:/Users/Rita/Desktop/Assignment-3/YouthUnemployment2015_2011_2008_2004.xlsx", col_names = TRUE)
```

```{r controls, results='asis', tidy=TRUE, echo=FALSE}
# Read control variables data

Controlvariables <- read_excel("C:/Users/Rita/Desktop/Assignment-3/Controlvariables.xlsx", col_names = TRUE)

```

```{r dataset1, results='asis', tidy=TRUE, echo=FALSE}
# Merge the dataset of electoral results with the dataset of unemployment rates. Change columns as numeric and clean one column

Spain_data_1 <- merge(Turnout2004_2008_2011_2015, YouthUnemployment2004_2015, by=c("Region","Year"), all=TRUE)
```

```{r dataset2, results='asis', tidy=TRUE, echo=FALSE}
# Merge the dataset of electoral results with the dataset of controls

Spain_data <- merge(Spain_data_1, Controlvariables, by=c("Region","Year"), all=TRUE)
```

```{r adjustments, results='asis', tidy=TRUE, echo=FALSE}
#Final adjustments.  Change columns as numeric and clean one column

Spain_data$Unempl_rate_total<- as.numeric(Spain_data$Unempl_rate_total)
Spain_data$Unempl_rate_less25 <- as.numeric(Spain_data$Unempl_rate_less25)
Spain_data$Unempl_rate_16_19 <- as.numeric(Spain_data$Unempl_rate_16_19)
Spain_data$Unempl_rate_20_24 <- as.numeric(Spain_data$Unempl_rate_20_24)

Spain_data <- Spain_data[, -c(7,7)]
```

```{r fix, results='asis', tidy=TRUE, echo=FALSE}
# Create one dummy for each year
Spain_data["four"] <- as.numeric(Spain_data$Year == 2004)
Spain_data["eight"] <- as.numeric(Spain_data$Year == 2008)
Spain_data["eleven"] <- as.numeric(Spain_data$Year == 2011)
Spain_data["fifteen"] <- as.numeric(Spain_data$Year == 2015)

Reg3 <- lm(Turnout ~ Unempl_rate_less25 + GrowthGDPAnnual + PctUniversityGraduates + Region, data = Spain_data)
summary(Reg3)
```

```{r language, results='asis', tidy=TRUE, echo=FALSE}
# Create one dummy for each year
Spain_data["language"] <- as.numeric(Spain_data$Region == "Galicia" | Spain_data$Region =="Catalunya" | Spain_data$Region =="Comunitat_Valenciana" | Spain_data$Region =="Pais_Vasco")


Reg3 <- lm(Turnout ~ Unempl_rate_less25 + GrowthGDPAnnual + PctUniversityGraduates + language +Region, data = Spain_data)
summary(Reg3)
```

cor(Spain_data$PctUniversityGraduates, Spain_data$Unempl_rate_less25)