
---
title: "Regression"
author: "Rita Alvarez and Rafael Schmuziger"
date: "November 11, 2016"
output: pdf_document
---

```{r options, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(message = FALSE)
# opts_chunk$set(tidy=FALSE)
# opts_chunk$set(fig.path='figs/', cache.path='cache/graphics-', 
#         fig.align='center', fig.width = 5, fig.height = 5, fig.show = 'hold',
#         cache = TRUE, par = TRUE)
```

```{r library, message=FALSE, echo=FALSE, include=FALSE}
library(pxR)
library(MicroDatosEs)
library(XML)
library(zoo)
library(rvest)
library(dplyr)
library(magrittr)
library(foreign)
library(readxl)
library(ggplot2)
library(pastecs)
library(stargazer)
```


```{r set wd, message=FALSE, echo=FALSE, include=FALSE}
setwd('C:/Users/Rita/Desktop/Final-Data-Project')
```

```{r turnout data, results='asis', tidy=TRUE, echo=FALSE}
# Read Turnout data

Turnout2004_2008_2011_2015 <- read_excel("C:/Users/Rita/Desktop/Assignment-3/ElectionsResult_2015_2011_2008_2004.xlsx", col_names = TRUE)
```

```{r unemployment data, results='asis', tidy=TRUE, echo=FALSE}
# Read Unemployment data

YouthUnemployment2004_2015 <- read_excel("C:/Users/Rita/Desktop/Assignment-3/YouthUnemployment2015_2011_2008_2004.xlsx", col_names = TRUE)
```

```{r dataset, results='asis', tidy=TRUE, echo=FALSE}
# Merge the dataset of electoral results with the dataset of unemployment rates. Change columns as numeric and clean one column

Spain_data <- merge(Turnout2004_2008_2011_2015, YouthUnemployment2004_2015, by=c("Region","Year"), all=TRUE)

Spain_data$Unempl_rate_total<- as.numeric(Spain_data$Unempl_rate_total)
Spain_data$Unempl_rate_less25 <- as.numeric(Spain_data$Unempl_rate_less25)
Spain_data$Unempl_rate_16_19 <- as.numeric(Spain_data$Unempl_rate_16_19)
Spain_data$Unempl_rate_20_24 <- as.numeric(Spain_data$Unempl_rate_20_24)

Spain_data <- Spain_data[, -c(7,7)]
```

$$
Turnout_{it}= \beta_{0}+\beta_{1}Youth\ Unemployment\ Rate_{it}+\epsilon_{it}
$$

```{r}
Reg1 <- lm(Turnout ~ Unempl_rate_less25, data = Spain_data)
```

```{r}
summary(Reg1)
```

```{r stargazer, results='asis', tidy=TRUE, echo=FALSE, header = FALSE}
stargazer(Reg1)
```
$$
Turnout_{it}= \beta_{0}+\beta_{1}Youth\ Unemployment\ Rate_{it}+\delta_{i} + \epsilon_{it}
$$

```{r}
Reg2 <- lm(Turnout ~ Unempl_rate_less25 + Region, data = Spain_data)
```

```{r}
summary(Reg2)
```

```{r stargazer, results='asis', tidy=TRUE, echo=FALSE, header = FALSE}
stargazer(Reg1, Reg2)
```